New Target Nomi
numerai/numerox pull request #49
Opened 2020-11-12 18:44 UTC by suud

# Description
Starting for round 238, the official target will be Nomi. This will bring the following changes:

- training and tournament files will contain the target column `target` instead of `target_kazutsugi`
- predictions should be submitted with the column header `prediction` instead of `prediction_kazutsugi`

# Changes
This pull request defines a new tournament `nomi` and changes the mentioned column headers.

I'm somehow confused as the column name for the predictions was `'probability_' + tourn` but I expected it to be `'prediction_' + tourn`. Probably this just doesn't get checked.

2020-11-14 19:06 UTC, suud commented
I've just realised that Nomi isn't a new tournament. So I removed the tournament from the list.
This pull request now **only updates the column names**.

2020-11-17 01:44 UTC, pschork requested changes
Thanks for this PR. Please see my comments

2020-11-17 01:44 UTC, pschork commented on numerox/data.py
> +            rename_map['target_' + name] = name
Please remove tournament number check and just `rename_map['target'] = name`

2020-11-17 01:44 UTC, pschork commented on numerox/prediction.py
> +            df = self.df.iloc[:, 0].to_frame('probability_' + tourn)
Please remove the tournament number check and just `df = self.df.iloc[:, 0].to_frame('prediction')`

Yea `probability_` was an old column header prefix from olden days.

2020-11-17 15:27 UTC, suud commented
Thanks for your feedback. I've updated the code.

2020-11-20 01:12 UTC, jrathgeber commented
Just saw this. Yes please.

2020-12-03 15:44 UTC, suud commented
@pschork I think this can be merged to close #50.

2020-12-03 17:34 UTC, pschork approved these changes

2020-12-03 17:34 UTC, merged